version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/countly/
permissions:
   - object: /home/ec2-user/countly/
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file
hooks:
  ApplicationStop:
    - location: codedeploy/stop_app
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/install
      timeout: 300
      runas: root
    - location: codedeploy/start_app
      timeout: 300
      runas: root
